device: 'cpu'
model_save_path: 'model/save.pt'
bin_model_save_path: 'model/save.bin'
only_quiet: yes 

train_bin_data_path: /ssd/Minic/train_data/all/all.bin
validation_bin_data_path: /ssd/Minic/train_data/validation/depth16/validation.txt.bin

shuffle_buffer_size: 100000
enable_mirroring: yes
num_workers: 8
batch_size: 256
lambda_: 1

visual_directory: 'visual'

epochs: 10000000
save_rate: 20000
report_rate: 50
test_rate: 500
max_queue_size: 128

learning_rate: 0.1
